// <auto-generated />
using System;
using IzhevskEventRadar.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IzhevskEventRadar.DataBase.Migrations
{
    [DbContext(typeof(EventRadarDbContext))]
    [Migration("20251021120436_EventsTable")]
    partial class EventsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IzhevskEventRadar.DataBase.DataModels.EventDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("IzhevskEventRadar.DataBase.DataModels.GroupDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("InternalId");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalId = "verbasong"
                        },
                        new
                        {
                            Id = 2,
                            InternalId = "club204542457"
                        },
                        new
                        {
                            Id = 3,
                            InternalId = "solenoe_nebo"
                        },
                        new
                        {
                            Id = 4,
                            InternalId = "hmelion"
                        },
                        new
                        {
                            Id = 5,
                            InternalId = "club93669411"
                        },
                        new
                        {
                            Id = 6,
                            InternalId = "grigger"
                        },
                        new
                        {
                            Id = 7,
                            InternalId = "laskina.voice"
                        },
                        new
                        {
                            Id = 8,
                            InternalId = "club179780208"
                        },
                        new
                        {
                            Id = 9,
                            InternalId = "sunnyjain"
                        },
                        new
                        {
                            Id = 10,
                            InternalId = "club700270"
                        },
                        new
                        {
                            Id = 11,
                            InternalId = "club39964891"
                        },
                        new
                        {
                            Id = 12,
                            InternalId = "waltzing_dogs"
                        },
                        new
                        {
                            Id = 13,
                            InternalId = "jazz18"
                        },
                        new
                        {
                            Id = 14,
                            InternalId = "bardfest_babushkinadacha"
                        },
                        new
                        {
                            Id = 15,
                            InternalId = "bluescrew"
                        },
                        new
                        {
                            Id = 16,
                            InternalId = "mcilchante"
                        },
                        new
                        {
                            Id = 17,
                            InternalId = "snyafrikantza"
                        },
                        new
                        {
                            Id = 18,
                            InternalId = "club77921354"
                        },
                        new
                        {
                            Id = 19,
                            InternalId = "sasha_afrikanets"
                        },
                        new
                        {
                            Id = 20,
                            InternalId = "favorityluny"
                        },
                        new
                        {
                            Id = 21,
                            InternalId = "izhjazzfest"
                        },
                        new
                        {
                            Id = 22,
                            InternalId = "aes_18"
                        },
                        new
                        {
                            Id = 23,
                            InternalId = "udmurtskayatoska"
                        },
                        new
                        {
                            Id = 24,
                            InternalId = "tyloburdo"
                        },
                        new
                        {
                            Id = 25,
                            InternalId = "kareninband"
                        },
                        new
                        {
                            Id = 26,
                            InternalId = "bereg_rock"
                        },
                        new
                        {
                            Id = 27,
                            InternalId = "jahra_reggae"
                        },
                        new
                        {
                            Id = 28,
                            InternalId = "csdr_izh"
                        },
                        new
                        {
                            Id = 29,
                            InternalId = "panamakanal"
                        },
                        new
                        {
                            Id = 30,
                            InternalId = "club123198303"
                        },
                        new
                        {
                            Id = 31,
                            InternalId = "club228777277"
                        },
                        new
                        {
                            Id = 32,
                            InternalId = "ryabchik721"
                        },
                        new
                        {
                            Id = 33,
                            InternalId = "polina_vanez"
                        },
                        new
                        {
                            Id = 34,
                            InternalId = "club224889358"
                        },
                        new
                        {
                            Id = 35,
                            InternalId = "club229240924"
                        },
                        new
                        {
                            Id = 36,
                            InternalId = "club224378859"
                        },
                        new
                        {
                            Id = 37,
                            InternalId = "irisovopole"
                        },
                        new
                        {
                            Id = 38,
                            InternalId = "club224080404"
                        },
                        new
                        {
                            Id = 39,
                            InternalId = "club179780208"
                        },
                        new
                        {
                            Id = 40,
                            InternalId = "udmfil"
                        });
                });

            modelBuilder.Entity("IzhevskEventRadar.DataBase.DataModels.PostDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
