// <auto-generated />
using System;
using IzhevskEventRadar.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IzhevskEventRadar.DataBase.Migrations
{
    [DbContext(typeof(EventRadarDbContext))]
    [Migration("20251027084436_UpdateGroupsTable")]
    partial class UpdateGroupsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IzhevskEventRadar.DataBase.DataModels.EventDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("IzhevskEventRadar.DataBase.DataModels.GroupDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("InternalId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalId = "verbasong",
                            IsActive = false
                        },
                        new
                        {
                            Id = 2,
                            InternalId = "club204542457",
                            IsActive = false
                        },
                        new
                        {
                            Id = 3,
                            InternalId = "solenoe_nebo",
                            IsActive = false
                        },
                        new
                        {
                            Id = 4,
                            InternalId = "hmelion",
                            IsActive = false
                        },
                        new
                        {
                            Id = 5,
                            InternalId = "club93669411",
                            IsActive = false
                        },
                        new
                        {
                            Id = 6,
                            InternalId = "grigger",
                            IsActive = false
                        },
                        new
                        {
                            Id = 7,
                            InternalId = "laskina.voice",
                            IsActive = false
                        },
                        new
                        {
                            Id = 8,
                            InternalId = "club179780208",
                            IsActive = false
                        },
                        new
                        {
                            Id = 9,
                            InternalId = "sunnyjain",
                            IsActive = false
                        },
                        new
                        {
                            Id = 10,
                            InternalId = "club700270",
                            IsActive = false
                        },
                        new
                        {
                            Id = 11,
                            InternalId = "club39964891",
                            IsActive = false
                        },
                        new
                        {
                            Id = 12,
                            InternalId = "waltzing_dogs",
                            IsActive = false
                        },
                        new
                        {
                            Id = 13,
                            InternalId = "jazz18",
                            IsActive = false
                        },
                        new
                        {
                            Id = 14,
                            InternalId = "bardfest_babushkinadacha",
                            IsActive = false
                        },
                        new
                        {
                            Id = 15,
                            InternalId = "bluescrew",
                            IsActive = false
                        },
                        new
                        {
                            Id = 16,
                            InternalId = "mcilchante",
                            IsActive = false
                        },
                        new
                        {
                            Id = 17,
                            InternalId = "snyafrikantza",
                            IsActive = false
                        },
                        new
                        {
                            Id = 18,
                            InternalId = "club77921354",
                            IsActive = false
                        },
                        new
                        {
                            Id = 19,
                            InternalId = "sasha_afrikanets",
                            IsActive = false
                        },
                        new
                        {
                            Id = 20,
                            InternalId = "favorityluny",
                            IsActive = false
                        },
                        new
                        {
                            Id = 21,
                            InternalId = "izhjazzfest",
                            IsActive = false
                        },
                        new
                        {
                            Id = 22,
                            InternalId = "aes_18",
                            IsActive = false
                        },
                        new
                        {
                            Id = 23,
                            InternalId = "udmurtskayatoska",
                            IsActive = false
                        },
                        new
                        {
                            Id = 24,
                            InternalId = "tyloburdo",
                            IsActive = false
                        },
                        new
                        {
                            Id = 25,
                            InternalId = "kareninband",
                            IsActive = false
                        },
                        new
                        {
                            Id = 26,
                            InternalId = "bereg_rock",
                            IsActive = false
                        },
                        new
                        {
                            Id = 27,
                            InternalId = "jahra_reggae",
                            IsActive = false
                        },
                        new
                        {
                            Id = 28,
                            InternalId = "csdr_izh",
                            IsActive = false
                        },
                        new
                        {
                            Id = 29,
                            InternalId = "panamakanal",
                            IsActive = false
                        },
                        new
                        {
                            Id = 30,
                            InternalId = "club123198303",
                            IsActive = false
                        },
                        new
                        {
                            Id = 31,
                            InternalId = "club228777277",
                            IsActive = false
                        },
                        new
                        {
                            Id = 32,
                            InternalId = "ryabchik721",
                            IsActive = false
                        },
                        new
                        {
                            Id = 33,
                            InternalId = "polina_vanez",
                            IsActive = false
                        },
                        new
                        {
                            Id = 34,
                            InternalId = "club224889358",
                            IsActive = false
                        },
                        new
                        {
                            Id = 35,
                            InternalId = "club229240924",
                            IsActive = false
                        },
                        new
                        {
                            Id = 36,
                            InternalId = "club224378859",
                            IsActive = false
                        },
                        new
                        {
                            Id = 37,
                            InternalId = "irisovopole",
                            IsActive = false
                        },
                        new
                        {
                            Id = 38,
                            InternalId = "club224080404",
                            IsActive = false
                        },
                        new
                        {
                            Id = 39,
                            InternalId = "club179780208",
                            IsActive = false
                        },
                        new
                        {
                            Id = 40,
                            InternalId = "udmfil",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("IzhevskEventRadar.DataBase.DataModels.PostDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
